### ISSUE TITLE
the synthesis result is bad when using pretrain model 

### ISSUE THREAD

**Issue by mnfutao** [keonlee9420/StyleSpeech#6]
hello sir, thanks for your sharing.

i meet a problem when i using pretrain model to synthsize demo file. the effect of synthesized wav is so bad.

do you konw what problem happened?

pretrain_model: output/ckpt/LibriTTS_meta_learner/200000.pth.tar
ref_audio: [ref_audio.zip](https://github.com/keonlee9420/StyleSpeech/files/7224736/ref_audio.zip)
demo_txt: {Promises are often like the butterfly, which disappear after beautiful hover. No matter the ending is perfect or not, you cannot disappear from my world.}
demo_wav:[demo.zip](https://github.com/keonlee9420/StyleSpeech/files/7224741/demo.zip)

**Comment by keonlee9420** [comment]
Hi @mnfutao , thanks for sharing results. It is mainly because of the sampling rate where 22050Hz is used in this repo but the paper used 16kHz. This makes the model capacity relatively smaller, and hence the output quality is degraded. In my point of view, there are two options: 1. increase model size, 2. training model with more steps than 200k. It might work at certain level and increase the output quality.

**Comment by mnfutao** [comment]
thanks， i will try it with increasing model size. 
i have already trained the model more than 200k， but the quality is still bad :(

**Comment by keonlee9420** [comment]
That's bad news. Please let me know if increasing the model size helps.

**Comment by keonlee9420** [comment]
Close due to inactivity.
